name: zero
description: 

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  page_view_indicator: ^2.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4



flutter:

  assets:
  - assets/images/plasticbottle1.jpg
  - assets/images/plasticbottle2.jpg
  - assets/images/plasticbottle3.jpg
  - assets/images/reward1.jpg
  - assets/images/reward2.jpg
  - assets/images/reward3.jpg
  - assets/images/reward4.jpg



  uses-material-design: true

